#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# yarn install
# npx lint-staged
# yarn build

# make up-d \
#   y/install \
#   de/c c="npx lint-staged" \
#   y/build

CONTAINER_NAME="react-docker-project"
DC="docker compose"

${DC} up -d
${DC} exec -T ${CONTAINER_NAME} sh -c "yarn install"
${DC} exec -T ${CONTAINER_NAME} sh -c "npx lint-staged"
${DC} exec -T ${CONTAINER_NAME} sh -c "yarn build"