name: 'Format By ESLint and Prettier and CSpell'

on: push

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 18.16.0
          npm-version: 9.6.7
      - name: Format
        run: |
          yarn install --frozen-lockfile
          yarn fix
